// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package fyneterm

import "fyne.io/fyne/v2"

var resourceActiveEnJson = &fyne.StaticResource{
	StaticName: "active.en.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Terminal\"\n}\n"),
}
var ResourceActiveFrJson = &fyne.StaticResource{
	StaticName: "active.fr.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Terminale\"\n}\n"),
}
var ResourceActiveRuJson = &fyne.StaticResource{
	StaticName: "active.ru.json",
	StaticContent: []byte(
		"{\n  \"Title\": \"Fyne Терминал\"\n}\n"),
}
