::https://github.com/ddkwork/tools/blob/master/gopls/doc/analyzers.md
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -diff ./...
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix ./...