// Code generated by fynehelper; DO NOT EDIT.

package fynetree

import (
	"sync"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/widget"
	"github.com/drognisep/fynehelpers/generation"
	"github.com/drognisep/fynehelpers/layouthelp"
)

var _ fyne.Widget = (*branchNode)(nil)
var _ fyne.Tappable = (*branchNode)(nil)

type branchNode struct {
	widget.BaseWidget

	mux    sync.RWMutex
	id     widget.TreeNodeID
	render *branchNodeRenderer
	tree   *BranchTree
}

func (t *branchNode) CreateRenderer() fyne.WidgetRenderer {
	t.render = newBranchNodeRenderer()
	return t.render
}

func newBranchNode(tree *BranchTree) *branchNode {
	node := &branchNode{
		tree: tree,
	}
	node.ExtendBaseWidget(node)
	return node
}

func (t *branchNode) update(id widget.TreeNodeID, model generation.TreeModel) {
	t.mux.Lock()
	t.id = id
	if t.render != nil {
		t.render.label.SetText(model.DisplayString())
		t.render.icon.SetResource(model.DisplayIcon())
	}
	t.mux.Unlock()
	t.Refresh()
}

func (t *branchNode) Tapped(event *fyne.PointEvent) {
	t.mux.RLock()
	id := t.id
	t.mux.RUnlock()
	t.tree.Tapped(id, event)
}

var _ fyne.WidgetRenderer = (*branchNodeRenderer)(nil)

type branchNodeRenderer struct {
	icon    *widget.Icon
	label   *widget.Label
	layout  fyne.Layout
	objects []fyne.CanvasObject
}

func newBranchNodeRenderer() *branchNodeRenderer {
	render := &branchNodeRenderer{
		icon: &widget.Icon{},
		label: &widget.Label{
			Alignment: fyne.TextAlignLeading,
			TextStyle: fyne.TextStyle{},
		},
		layout: layout.NewHBoxLayout(),
	}
	render.objects = []fyne.CanvasObject{render.icon, render.label}
	return render
}

func (r *branchNodeRenderer) Destroy() {
	r.icon = nil
	r.label = nil
	r.layout = nil
	r.objects = nil
}

func (r *branchNodeRenderer) Layout(parent fyne.Size) {
	r.layout.Layout(r.objects, parent)
}

func (r *branchNodeRenderer) MinSize() fyne.Size {
	return layouthelp.AccumulateWidth(r.icon.MinSize(), r.label.MinSize())
}

func (r *branchNodeRenderer) Objects() []fyne.CanvasObject {
	return r.objects
}

func (r *branchNodeRenderer) Refresh() {
	for _, obj := range r.objects {
		obj.Refresh()
	}
}
