package stream

import (
	_ "embed"
	"fmt"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/ddkwork/golibrary/mylog"
)

type GeneratedFile struct {
	*Buffer
	packageName string
	filePath    string
}

func (g *GeneratedFile) SetFilePath(filePath string) *GeneratedFile {
	g.filePath = filePath
	return g
}

func (g *GeneratedFile) SetPackageName(packageName string) *GeneratedFile {
	g.packageName = packageName
	return g
}

func NewGeneratedFile() (g *GeneratedFile) {
	return &GeneratedFile{
		Buffer: NewBuffer(""),
	}
}

func (g *GeneratedFile) P(v ...any) {
	for _, x := range v {
		mylog.Check2(fmt.Fprint(g, x))
	}
	mylog.Check2(fmt.Fprintln(g))
}

func (g *GeneratedFile) Types(name string, TypeTooltipMap *OrderedMap[string, string]) {
	mylog.Call(func() {
		var (
			Types    []string
			tooltips []string
		)
		for _, kv := range TypeTooltipMap.List() {
			Types = append(Types, kv.Key)
			tooltips = append(tooltips, kv.Value)
		}
		//Types = append(Types, InvalidType)
		//tooltips = append(tooltips, InvalidType)
		for i, Type := range Types {
			Types[i] = ToCamelUpper(Type, false)
		}
		TypeNameUpper := ToCamelUpper(name, false)
		InvalidType := "Invalid" + TypeNameUpper + "Type"
		if g.packageName == "" {
			g.packageName = GetPackageName()
		}
		g.P("package ", g.packageName)
		g.P("")

		g.P("import (")
		g.P(strconv.Quote("golang.org/x/exp/constraints"))
		g.P(strconv.Quote("strings"))
		g.P(")")
		g.P("")

		g.P("// Code generated by GeneratedFile types - DO NOT EDIT.")

		g.P("")
		g.P("type ", TypeNameUpper, "Type byte")
		g.P("")
		g.P("const (")
		for i, Type := range Types {
			if i == 0 {
				g.P(" ", Type, "Type", " ", TypeNameUpper, "Type = iota")
				continue
			}
			g.P(" "+Type, "Type")
		}
		g.P(" ", InvalidType)

		g.P(")")
		g.P("")

		g.P("func ConvertInteger2", TypeNameUpper, "Type[T constraints.Integer](v T)", TypeNameUpper, "Type  {")
		g.P("  return ", TypeNameUpper, "Type(v)")
		g.P("}")
		g.P("")

		g.P("func (t ", TypeNameUpper, "Type) AssertType(Types string) ", TypeNameUpper, "Type {")
		g.P(" for _, Type := range t.Types() {")
		g.P("  if strings.ToLower(Types) == strings.ToLower(Type.String()) {")
		g.P("   return Type")
		g.P("  }")
		g.P(" }")
		g.P(" return " + InvalidType)
		g.P("}")
		g.P("")

		g.P("func (t ", TypeNameUpper, "Type) String() string {")
		g.P(" switch t {")
		for _, Type := range Types {
			g.P(" case ", Type, "Type:")
			g.P("  return ", strconv.Quote(Type))
		}
		g.P(" default:")
		g.P("  return ", strconv.Quote(InvalidType))
		g.P(" }")
		g.P("}")
		g.P("")

		if len(tooltips) > 0 {
			g.P("func (t ", TypeNameUpper, "Type) Tooltip() string {")
			g.P(" switch t {")
			for i, Type := range Types {
				g.P(" case ", Type, "Type:")
				g.P("  return ", strconv.Quote(tooltips[i]))
			}
			g.P(" default:")
			g.P("  return ", strconv.Quote(InvalidType))
			g.P(" }")
			g.P("}")
			g.P("")
		}

		g.P("func (t ", TypeNameUpper, "Type) Names() []string {")
		g.P(" return []string{")
		for _, Type := range Types {
			g.P("  ", strconv.Quote(Type), ",")
		}
		g.P(" }")
		g.P("}")
		g.P("")

		g.P("func (t ", TypeNameUpper, "Type) Types() []", TypeNameUpper, "Type {")
		g.P(" return []", TypeNameUpper, "Type{")
		for _, Type := range Types {
			g.P("  ", Type, "Type,")
		}
		g.P(" }")
		g.P("}")
		g.P("")

		g.P("func (t ", TypeNameUpper, "Type) SvgFileName() string {")
		g.P(" switch t {")
		for _, Type := range Types {
			g.P(" case ", Type, "Type:")
			g.P("  return ", strconv.Quote(Type))
		}
		g.P("	default:")
		g.P("  return ", strconv.Quote(InvalidType))
		g.P(" }")
		g.P("}")
		g.P("")
		WriteGoFile(filepath.Join(g.filePath, name+"_enum_gen.go"), g.Buffer)
		g.Reset()
	})
}

func (g *GeneratedFile) ReadTemplates(path, pkg string) {
	pkg = strings.TrimSuffix(pkg, "_test")
	mylog.Call(func() {
		s := NewBuffer("package " + pkg + "_test")
		s.NewLine()
		s.WriteStringLn(`
   import (
			"github.com/ddkwork/golibrary/stream"
		)`)
		s.NewLine()

		s.WriteStringLn("func generateIR(path string,callBack func(b*stream.Buffer)) {")
		s.WriteStringLn("g := stream.NewGeneratedFile()")
		lines := NewBuffer(path).ToLines()
		for _, line := range lines {
			needNewLine := false
			if line == "" {
				needNewLine = true
			}
			if strings.HasPrefix(line, "package") {
				packageName := "package " + GetPackageName()
				line = "g.P(" + strconv.Quote(packageName) + ")"
			} else {
				line = strings.ReplaceAll(line, "\t", " ")
				line = "g.P(" + strconv.Quote(line) + ")"

			}
			s.WriteStringLn(line)
			if needNewLine {
				s.NewLine()
			}
		}
		s.NewLine()
		s.WriteStringLn("callBack(g.Buffer)")
		// s.WriteStringLn("stream.WriteGoFile(" + strconv.Quote(BaseName(path)+"_gen.go") + ", g.Buffer())")
		s.WriteStringLn("stream.WriteGoFile(path, g.Buffer)")
		s.WriteStringLn("}")
		println(s.String())
	})
}

func Unquote(line string) string {
	begin := strings.Index(line, `\"`)
	if begin < 0 {
		return line
	}
	split := strings.Split(line, `\"`)
	ss := NewBuffer("")
	for _, s := range split {
		if strings.Contains(s, `"`) {
			s = strings.ReplaceAll(s, `"`, ``)
			ss.WriteString(s)
		} else {
			ss.WriteString("strconv.Quote(")
			ss.WriteString(strconv.Quote(s))
			ss.WriteString(")")
		}
	}
	return ss.String()
}
