package table

import (
	"cogentcore.org/core/gi"
	"cogentcore.org/core/icons"
	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile enum - DO NOT EDIT.

type TableDocKind byte

const (
	InitKind TableDocKind = iota
	WalkerKind
	CtxKind
	AdderKind
	RemoverKind
	UpdaterKind
	FinderKind
	TableCtxKind
	InvalidTableDocKind
)

func ConvertInteger2TableDocKind[T constraints.Integer](v T) TableDocKind {
	return TableDocKind(v)
}

func (k TableDocKind) AssertKind(kinds string) TableDocKind {
	for _, kind := range k.Kinds() {
		if kinds == kind.String() {
			return kind
		}
	}
	return InvalidTableDocKind
}

func (k TableDocKind) ChooserItem() []gi.ChooserItem {
	chooserItems := make([]gi.ChooserItem, 0)
	for _, kind := range k.Kinds() {
		chooserItems = append(chooserItems, gi.ChooserItem{
			Value:           kind.String(),
			Label:           "",
			Icon:            icons.Icon(k.SvgFileName()),
			Tooltip:         kind.String(),
			Func:            nil,
			SeparatorBefore: false,
		})
	}
	return chooserItems
}

func (k TableDocKind) String() string {
	switch k {
	case InitKind:
		return "Init"
	case WalkerKind:
		return "Walker"
	case CtxKind:
		return "Ctx"
	case AdderKind:
		return "Adder"
	case RemoverKind:
		return "Remover"
	case UpdaterKind:
		return "Updater"
	case FinderKind:
		return "Finder"
	case TableCtxKind:
		return "TableCtx"
	default:
		return "InvalidTableDocKind"
	}
}

func (k TableDocKind) Keys() []string {
	return []string{
		"Init",
		"Walker",
		"Ctx",
		"Adder",
		"Remover",
		"Updater",
		"Finder",
		"TableCtx",
		"InvalidTableDocKind",
	}
}

func (k TableDocKind) Kinds() []TableDocKind {
	return []TableDocKind{
		InitKind,
		WalkerKind,
		CtxKind,
		AdderKind,
		RemoverKind,
		UpdaterKind,
		FinderKind,
		TableCtxKind,
		InvalidTableDocKind,
	}
}

func (k TableDocKind) SvgFileName() string {
	switch k {
	case InitKind:
		return "Init"
	case WalkerKind:
		return "Walker"
	case CtxKind:
		return "Ctx"
	case AdderKind:
		return "Adder"
	case RemoverKind:
		return "Remover"
	case UpdaterKind:
		return "Updater"
	case FinderKind:
		return "Finder"
	case TableCtxKind:
		return "TableCtx"
	default:
		return "InvalidTableDocKind"
	}
}
