// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.5.1-go
// source: session.myreflect

package session

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group1 *Session_Group1 `protobuf:"group,1,opt,name=Group1,json=group1" json:"group1,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetGroup1() *Session_Group1 {
	if x != nil {
		return x.Group1
	}
	return nil
}

type Packed2Obj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group2  []*Packed2Obj_Group2 `protobuf:"group,2,rep,name=Packed2,json=group2" json:"group2,omitempty"`
	Binary3 *string              `protobuf:"bytes,3,opt,name=binary3" json:"binary3,omitempty"`
}

func (x *Packed2Obj) Reset() {
	*x = Packed2Obj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packed2Obj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packed2Obj) ProtoMessage() {}

func (x *Packed2Obj) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packed2Obj.ProtoReflect.Descriptor instead.
func (*Packed2Obj) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1}
}

func (x *Packed2Obj) GetGroup2() []*Packed2Obj_Group2 {
	if x != nil {
		return x.Group2
	}
	return nil
}

func (x *Packed2Obj) GetBinary3() string {
	if x != nil && x.Binary3 != nil {
		return *x.Binary3
	}
	return ""
}

type Session_Group1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Binary1 *string     `protobuf:"bytes,1,opt,name=binary1" json:"binary1,omitempty"`
	Packed2 *Packed2Obj `protobuf:"bytes,2,opt,name=packed2" json:"packed2,omitempty"`
	Varint3 *uint64     `protobuf:"varint,3,opt,name=varint3" json:"varint3,omitempty"`
	Binary4 *string     `protobuf:"bytes,4,opt,name=binary4" json:"binary4,omitempty"`
	Varint5 *uint64     `protobuf:"varint,5,opt,name=varint5" json:"varint5,omitempty"`
}

func (x *Session_Group1) Reset() {
	*x = Session_Group1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session_Group1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session_Group1) ProtoMessage() {}

func (x *Session_Group1) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session_Group1.ProtoReflect.Descriptor instead.
func (*Session_Group1) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Session_Group1) GetBinary1() string {
	if x != nil && x.Binary1 != nil {
		return *x.Binary1
	}
	return ""
}

func (x *Session_Group1) GetPacked2() *Packed2Obj {
	if x != nil {
		return x.Packed2
	}
	return nil
}

func (x *Session_Group1) GetVarint3() uint64 {
	if x != nil && x.Varint3 != nil {
		return *x.Varint3
	}
	return 0
}

func (x *Session_Group1) GetBinary4() string {
	if x != nil && x.Binary4 != nil {
		return *x.Binary4
	}
	return ""
}

func (x *Session_Group1) GetVarint5() uint64 {
	if x != nil && x.Varint5 != nil {
		return *x.Varint5
	}
	return 0
}

type Packed2Obj_Group2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Varint1 *uint64 `protobuf:"varint,1,opt,name=varint1" json:"varint1,omitempty"`
	Binary2 *string `protobuf:"bytes,2,opt,name=binary2" json:"binary2,omitempty"`
	Binary3 *string `protobuf:"bytes,3,opt,name=binary3" json:"binary3,omitempty"`
	Binary4 *string `protobuf:"bytes,4,opt,name=binary4" json:"binary4,omitempty"`
}

func (x *Packed2Obj_Group2) Reset() {
	*x = Packed2Obj_Group2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_session_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Packed2Obj_Group2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packed2Obj_Group2) ProtoMessage() {}

func (x *Packed2Obj_Group2) ProtoReflect() protoreflect.Message {
	mi := &file_session_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packed2Obj_Group2.ProtoReflect.Descriptor instead.
func (*Packed2Obj_Group2) Descriptor() ([]byte, []int) {
	return file_session_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Packed2Obj_Group2) GetVarint1() uint64 {
	if x != nil && x.Varint1 != nil {
		return *x.Varint1
	}
	return 0
}

func (x *Packed2Obj_Group2) GetBinary2() string {
	if x != nil && x.Binary2 != nil {
		return *x.Binary2
	}
	return ""
}

func (x *Packed2Obj_Group2) GetBinary3() string {
	if x != nil && x.Binary3 != nil {
		return *x.Binary3
	}
	return ""
}

func (x *Packed2Obj_Group2) GetBinary4() string {
	if x != nil && x.Binary4 != nil {
		return *x.Binary4
	}
	return ""
}

var File_session_proto protoreflect.FileDescriptor

var file_session_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xcc, 0x01, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x06, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0a, 0x32, 0x0f, 0x2e, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x31, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x31, 0x1a, 0x97, 0x01, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x31, 0x12,
	0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x31, 0x12, 0x25, 0x0a, 0x07, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x32, 0x4f, 0x62, 0x6a, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x32,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x33, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x34, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x35, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x35, 0x22, 0xc4,
	0x01, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x32, 0x4f, 0x62, 0x6a, 0x12, 0x2a, 0x0a,
	0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x32, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0a, 0x32, 0x12, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x32, 0x4f, 0x62, 0x6a, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x32, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x32, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x61,
	0x72, 0x79, 0x33, 0x1a, 0x70, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x32, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x76, 0x61, 0x72, 0x69, 0x6e, 0x74, 0x31, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x32, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x33, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x33, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x34, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e,
}

var (
	file_session_proto_rawDescOnce sync.Once
	file_session_proto_rawDescData = file_session_proto_rawDesc
)

func file_session_proto_rawDescGZIP() []byte {
	file_session_proto_rawDescOnce.Do(func() {
		file_session_proto_rawDescData = protoimpl.X.CompressGZIP(file_session_proto_rawDescData)
	})
	return file_session_proto_rawDescData
}

var file_session_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_session_proto_goTypes = []any{
	(*Session)(nil),           // 0: session
	(*Packed2Obj)(nil),        // 1: Packed2Obj
	(*Session_Group1)(nil),    // 2: session.Group1
	(*Packed2Obj_Group2)(nil), // 3: Packed2Obj.Packed2
}
var file_session_proto_depIdxs = []int32{
	2, // 0: session.group1:type_name -> session.Group1
	3, // 1: Packed2Obj.group2:type_name -> Packed2Obj.Packed2
	1, // 2: session.Group1.packed2:type_name -> Packed2Obj
	3, // [3:3] is the sub-protolist for method output_type
	3, // [3:3] is the sub-protolist for method input_type
	3, // [3:3] is the sub-protolist for extension type_name
	3, // [3:3] is the sub-protolist for extension extendee
	0, // [0:3] is the sub-protolist for field type_name
}

func init() { file_session_proto_init() }
func file_session_proto_init() {
	if File_session_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_session_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Packed2Obj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Session_Group1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_session_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Packed2Obj_Group2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_session_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_session_proto_goTypes,
		DependencyIndexes: file_session_proto_depIdxs,
		MessageInfos:      file_session_proto_msgTypes,
	}.Build()
	File_session_proto = out.File
	file_session_proto_rawDesc = nil
	file_session_proto_goTypes = nil
	file_session_proto_depIdxs = nil
}
