package httpClient

import (
	"strings"

	"golang.org/x/exp/constraints"
)

// Code generated by GeneratedFile types - DO NOT EDIT.

type SchemerType byte

const (
	HttpType SchemerType = iota
	HttpsType
	Socket4Type
	Socket5Type
	WebSocketType
	WebsocketTlsType
	TcpType
	TcpTlsType
	UdpType
	KcpType
	PipeType
	QuicType
	RpcType
	SshType
	InvalidSchemerType
)

func ConvertInteger2SchemerType[T constraints.Integer](v T) SchemerType {
	return SchemerType(v)
}

func (t SchemerType) AssertType(name string) SchemerType {
	for _, Type := range t.EnumTypes() {
		if strings.ToLower(name) == strings.ToLower(Type.String()) {
			return Type
		}
	}
	return InvalidSchemerType
}

func (t SchemerType) String() string {
	switch t {
	case HttpType:
		return "Http"
	case HttpsType:
		return "Https"
	case Socket4Type:
		return "Socket4"
	case Socket5Type:
		return "Socket5"
	case WebSocketType:
		return "WebSocket"
	case WebsocketTlsType:
		return "WebsocketTls"
	case TcpType:
		return "Tcp"
	case TcpTlsType:
		return "TcpTls"
	case UdpType:
		return "Udp"
	case KcpType:
		return "Kcp"
	case PipeType:
		return "Pipe"
	case QuicType:
		return "Quic"
	case RpcType:
		return "Rpc"
	case SshType:
		return "Ssh"
	default:
		return "InvalidSchemerType"
	}
}

func (t SchemerType) Tooltip() string {
	switch t {
	case HttpType:
		return "Http"
	case HttpsType:
		return "Https"
	case Socket4Type:
		return "Socket4"
	case Socket5Type:
		return "Socket5"
	case WebSocketType:
		return "WebSocket"
	case WebsocketTlsType:
		return "WebsocketTls"
	case TcpType:
		return "Tcp"
	case TcpTlsType:
		return "TcpTls"
	case UdpType:
		return "Udp"
	case KcpType:
		return "Kcp"
	case PipeType:
		return "Pipe"
	case QuicType:
		return "Quic"
	case RpcType:
		return "Rpc"
	case SshType:
		return "Ssh"
	default:
		return "InvalidSchemerType"
	}
}

func (t SchemerType) Names() []string {
	return []string{
		"Http",
		"Https",
		"Socket4",
		"Socket5",
		"WebSocket",
		"WebsocketTls",
		"Tcp",
		"TcpTls",
		"Udp",
		"Kcp",
		"Pipe",
		"Quic",
		"Rpc",
		"Ssh",
	}
}

func (t SchemerType) EnumTypes() []SchemerType {
	return []SchemerType{
		HttpType,
		HttpsType,
		Socket4Type,
		Socket5Type,
		WebSocketType,
		WebsocketTlsType,
		TcpType,
		TcpTlsType,
		UdpType,
		KcpType,
		PipeType,
		QuicType,
		RpcType,
		SshType,
	}
}

func (t SchemerType) SvgFileName() string {
	switch t {
	case HttpType:
		return "Http"
	case HttpsType:
		return "Https"
	case Socket4Type:
		return "Socket4"
	case Socket5Type:
		return "Socket5"
	case WebSocketType:
		return "WebSocket"
	case WebsocketTlsType:
		return "WebsocketTls"
	case TcpType:
		return "Tcp"
	case TcpTlsType:
		return "TcpTls"
	case UdpType:
		return "Udp"
	case KcpType:
		return "Kcp"
	case PipeType:
		return "Pipe"
	case QuicType:
		return "Quic"
	case RpcType:
		return "Rpc"
	case SshType:
		return "Ssh"
	default:
		return "InvalidSchemerType"
	}
}

func (l SchemerType) IsStream() bool {
	switch l {
	case InvalidSchemerType, HttpType, HttpsType:
		return false
	default:
		return true

	}
}

func (l SchemerType) IsContainer() bool {
	return l.IsStream()
}

func (l SchemerType) Containers() []SchemerType {
	return []SchemerType{
		WebSocketType,
		KcpType,
		PipeType,
		QuicType,
		RpcType,
		Socket4Type,
		Socket5Type,
		SshType,
		TcpType,
		TcpTlsType,
		UdpType,
		WebsocketTlsType,
	}
}
