// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package notes

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed  HarmonyOS_Sans_SC_Bold.ttf
var ttfBody []byte

var resourceGochiHandTtf = &fyne.StaticResource{
	StaticName:    "GochiHand.ttf",
	StaticContent: ttfBody,
}
