name: go-mod-ci

on:
  push:
    branches:
      - master
      - dev
    tags:
      - 'v*'
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**/*.cmd'
      - '**/*.bat'
      - '**/*.md'

  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**/*.cmd'
      - '**/*.bat'
      - '**/*.md'

env:
  RELEASE_ZIP_FILE_NAME: golibrary

jobs:
  test-on-multiple-os:
    name: Test on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

  package-and-release:
    needs: test-on-multiple-os
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Install dependencies
        run: go mod tidy

#      - name: Build
#        run: go build -o ${{ env.RELEASE_ZIP_FILE_NAME }}

      - name: Create source code archive
        run: zip -r ${{ env.RELEASE_ZIP_FILE_NAME }}-${{ github.ref_name }}.zip . -x '.git/**'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.RELEASE_ZIP_FILE_NAME }}-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.tk }}
